## NumPy Assignment II

In [3]:
import numpy as np
# Creating a vector of length 5 filled with arbitrary integers from 0 to 10
vec_5 = np.random.randint(0, 11, 5)
vec_5

array([6, 3, 6, 2, 6])

In [6]:
# Creating a vector of values ranging from 15 to 55
vec_range = np.arange(15, 56)
print(vec_range)
print("\n")

# Print all the values except the first and last
print(vec_range[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [10]:
# Create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print("\n")

# Compute the cumulative sum along axis 0
cum_sum = np.cumsum(arr, axis=0)
print(cum_sum)
print("\n")

# Sum over columns for each of the first two rows
sum_rows = np.sum(cum_sum[:2, :], axis=0)
print(sum_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


[ 6  9 12]


In [17]:
# Create two matrices
mat_A = np.array([[1, 2], [3, 4]])
mat_B = np.array([[5, 6], [7, 8]])

# Compute the matrix multiplication
mat_C = mat_A @ mat_B
print(mat_C)

[[19 22]
 [43 50]]
